
	INCLUDE	SHIKE2.INC
	INCLUDE	BIOS.INC
	INCLUDE	LEVEL.INC
	INCLUDE	DATA.INC


	PUBLIC	ED.CHAR
	EXTRN	EDINIT,CARTPAGE,VDPSYNC,LISTEN

ED.CHAR:CALL	EDINIT

ED.LOOP:LD	E,LEVELPAGE
	CALL	CARTPAGE
	CALL	SHOWSCR
	CALL	VDPSYNC
	LD	DE,RECEIVERS
	CALL	LISTEN
	JR	NZ,ED.LOOP
	RET


RECEIVERS:
	DB	0


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	EXTRN	GLINES,GETNCHAR,LOCATE,PRINTF,ARYHL,CHARCTL

SHOWSCR:LD	DE,0
	CALL	LOCATE

	LD	DE,(NCHAR)
	CALL	GETNCHAR
	PUSH	HL
	PUSH	HL
	POP	IY
	LD	E,(IY+CHAR.CONTROL)
	LD	D,(IY+CHAR.CONTROL+1)
	CALL	CHARCTL
	POP	IY
	PUSH	HL
	LD	A,(IY+MOV.DIR)
	LD	HL,DIRS
	CALL	ARYHL
	PUSH	HL
	LD	H,0
	LD	L,(IY+MOV.Z)
	PUSH	HL
	LD	L,(IY+MOV.Y)
	PUSH	HL
	LD	L,(IY+MOV.X)
	PUSH	HL
	LD	L,(IY+MOV.LEVEL)
	PUSH	HL
	LD	L,(IY+MOV.LEVEL+1)
	PUSH	HL
	LD	L,(IY+MOV.ROOM)
	PUSH	HL
	LD	L,(IY+MOV.ROOM+1)
	PUSH	HL
	LD	L,(IY+MOV.PAT)
	PUSH	HL
	LD	A,(NCHAR)
	LD	L,A
	PUSH	HL

	LD	DE,CINFO
	CALL	PRINTF

	LD	C,15
	LD	DE,CHARG
	JP	GLINES


CINFO:	DB	"CHAR",9,"%02d",10
	DB	"PATERN",9,"%02d",10
	DB	"LEVEL",9,"%02dX%02d",10
	DB	"ROOM",9,"%02dX%02d",10
	DB	"X",9,"%02d",10
	DB	"Y",9,"%02d",10
	DB	"Z",9,"%02d",10
	DB	"DIR",9,"%s",10
	DB	"CONTROL",9,"%s",0

;	       REP  X0  Y0    X1  Y1 IX0 IY0 IX1 IY1
CHARG:	DB	2,  60,  5,   76,  5,  0, 32,  0, 32
	DB	2,  60,  5,   60, 37, 16,  0, 16,  0
	DB	0

DIRS:	DW	RIGTH,LEFT,UP,DOWN,NODIR
RIGTH:	DB	"RIGTH",0
LEFT:	DB	"LEFT",0
UP:	DB	"UP",0
DOWN:	DB	"DOWN",0
NODIR:	DB	"NO DIR",0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	DSEG

NCHAR:	DB	0

