
	INCLUDE	BIOS.INC
	INCLUDE	SHIKE2.INC
	INCLUDE	LEVEL.INC
	INCLUDE	EVENT.INC

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	PUBLIC	ED.ROOM
	EXTRN	ADDGLISTEN,CARTPAGE,EDINIT,LISTEN,VDPSYNC

ED.ROOM:CALL	EDINIT
	LD	DE,RECEIVERS
	LD	BC,POSEVENT
	CALL	ADDGLISTEN

ED.LOOP:LD	E,LEVELPAGE
	CALL	CARTPAGE
	CALL	GETRDATA
	CALL	SHOWSCR
	CALL	VDPSYNC
	LD	DE,RECEIVERS
	CALL	LISTEN
	JR	NZ,ED.ROOM
	RET


RECEIVERS:
	DS	64*6
	DB	0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	EXTRN	EDSET,EDPAL,EDLEVEL

GETRDATA:
	LD	DE,(EDLEVEL)
	CALL	GETLEVEL
	RET	Z
	PUSH	HL
	POP	IY
	LD	A,(IY+LVL.PAL)
	LD	(EDPAL),A
	LD	A,(IY+LVL.GFX)
	LD	(EDSET),A
	LD	(LPTR),IY
	RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	EXTRN	PTRHL,PRINTF,LOCATE,EDLEVEL,GRID16

SHOWSCR:CALL	GRID16
	CALL	DRAWRMATRIX

	LD	DE,0
	CALL	LOCATE
	LD	HL,(LPTR)
	PUSH	HL
	LD	DE,TITLE
	CALL	PRINTF

	LD	DE,0054H
	CALL	LOCATE

	LD	DE,(EDLEVEL)
	LD	BC,(EDROOM)
	XOR	A
	CALL	GETROOM
	CALL	PTRHL
	PUSH	HL

	LD	DE,(EDLEVEL)
	LD	BC,(EDROOM)
	LD	A,1
	CALL	GETROOM
	CALL	PTRHL
	PUSH	HL

	LD	DE,(EDLEVEL)
	LD	BC,(EDROOM)
	LD	A,2
	CALL	GETROOM
	CALL	PTRHL
	PUSH	HL

	LD	H,0
	LD	DE,(EDROOM)
	LD	L,E
	PUSH	HL
	LD	L,D
	PUSH	HL
	LD	DE,ROOMI
	CALL	PRINTF
	RET

TITLE:	DB	9,"ROOM EDITOR: LEVEL %s",0
ROOMI:	DB	9,"ROOM",9,"     %03dX%03d",10
	DB	9,"HEIGHT 0",9,"%04d",10
	DB	9,"HEIGHT 1",9,"%04d",10
	DB	9,"HEIGHT 2",9,"%04d",0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	EXTRN	EDLEVEL,COLORGRID16

DRAWRMATRIX:
	LD	B,LVLYSIZ
	LD	DE,0

S.LOOPY:PUSH	BC
	PUSH	DE
	LD	B,LVLXSIZ

S.LOOPX:PUSH	BC
	PUSH	DE
	PUSH	DE
	LD	C,E
	LD	B,D
	LD	DE,(EDLEVEL)
	LD	A,0
	CALL	GETROOM
	POP	DE
	JR	Z,S.ENDX
	LD	A,(HL)
	INC	HL
	OR	(HL)
	CALL	NZ,COLORGRID16

S.ENDX:	POP	DE
	INC	D
	POP	BC
	DJNZ	S.LOOPX

	POP	DE
	INC	E
	POP	BC
	DJNZ	S.LOOPY
	RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;INPUT:	A = EVENT
;	DE = SCREEN POSITION

	CSEG
	EXTRN	EDROOM,ED.MAP,GRIDPOS

POSEVENT:
	PUSH	AF
	CALL	GRIDPOS
	POP	AF
	CP	MS_BUTTON1
	JR	NZ,P.1
	LD	(EDROOM),DE
	JP	ED.MAP

P.1:	LD	(EDROOM),DE
	RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	DSEG
LPTR:	DW	0


