
	INCLUDE	SHIKE2.INC
	INCLUDE BIOS.INC
	INCLUDE KBD.INC

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	PUBLIC	GAME
	EXTRN	CHARACTERS,NEWFRAME,MAP,MAPBUF,DELSPR
	EXTRN	INITCHAR,INITMOB

GAME:	CALL	DELSPR
	LD	DE,MAPBUF
	CALL	MAP
	CALL	INITMOB
	CALL	INITCHAR
G.LOOP: CALL	NEWFRAME
	CALL	CHARACTERS
	JR	G.LOOP

	PUBLIC	ENGINE
ENGINE:	RET

