ASFLAGS = -t

REL1 = shike2.rel movable.rel mob.rel zbuffer.rel editor.rel
REL2 = char.rel door.rel talk.rel game.rel level.rel map.rel object.rel
REL3 = kbd.rel mouse.rel stdlib.rel vdp.rel bios.rel script.rel
REL4 = edlevel.rel edneigh.rel edmap.rel edtsel.rel edfloor.rel edchar.rel
REL5 = eddoor.rel edobject.rel edtile.rel edpick.rel
REL =  $(REL1) $(REL2) $(REL3) $(REL4) $(REL5)

all : shike data

shike : shike2.com

data : leveldef.bin patset0.bin patset1.bin charset0.bin charset1.bin map0.bin map1.bin map2.bin map3.bin height0.bin height1.bin

dist :
	rm shike2.lzh
	lhpack a shike2.lzh *.dat *.asm *.inc makefile ld.cmd

palete.asm : ..\\gfx\\shike2.pl5
	copy ..\\gfx\\shike2.pl5
	db -lPALETES shike2.pl5 > palete.asm
	del shike2.pl5

fontspr.asm : font.obj
	fon2spr -lFONTSPR font.obj > fontspr.asm

font.asm : font.obj
	db -lFONTGR5 font.obj > font.asm

bload.obj : bload.asm
	as $(ASFLAGS) bload.asm
	ld bload.obj=bload.rel

########################################################
#load pages objects

loadpg11.obj : loadpg11.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg11.asm
	ld /RC000 loadpg11.obj=loadpg11.rel

loadpg10.obj : loadpg10.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg10.asm
	ld /RC000 loadpg10.obj=loadpg10.rel

loadpg9.obj : loadpg9.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg9.asm
	ld /RC000 loadpg9.obj=loadpg9.rel

loadpg8.obj : loadpg8.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg8.asm
	ld /RC000 loadpg8.obj=loadpg8.rel

loadpg7.obj : loadpg7.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg7.asm
	ld /RC000 loadpg7.obj=loadpg7.rel

loadpg6.obj : loadpg6.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg6.asm
	ld /RC000 loadpg6.obj=loadpg6.rel

loadpg5.obj : loadpg5.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg5.asm
	ld /RC000 loadpg5.obj=loadpg5.rel

loadpg4.obj : loadpg4.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg4.asm
	ld /RC000 loadpg4.obj=loadpg4.rel

loadpg3.obj : loadpg3.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg3.asm
	ld /RC000 loadpg3.obj=loadpg3.rel

loadpg2.obj : loadpg2.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg2.asm
	ld /RC000 loadpg2.obj=loadpg2.rel

loadpg1.obj : loadpg1.asm loader.asm shike2.inc bios.inc
	as $(ASFLAGS) loadpg1.asm
	ld /RC000 loadpg1.obj=loadpg1.rel

########################################################
#data objects

font.obj : ..\\gfx\\font.gl5
	del font.obj > NUL
	delgl5 ..\\gfx\\font.gl5 font.obj

charset1.obj : ..\\gfx\\charset1.gl5
	del charset1.obj > NUL
	delgl5 ..\\gfx\\charset1.gl5 charset1.obj

charset0.obj : ..\\gfx\\charset0.gl5
	del charset0.obj > NUL
	delgl5 ..\\gfx\\charset0.gl5 charset0.obj

patset1.obj : ..\\gfx\\patset1.gl5
	del patset1.obj > NUL
	delgl5 ..\\gfx\\patset1.gl5 patset1.obj

patset0.obj : ..\\gfx\\patset0.gl5
	del patset0.obj > NUL
	delgl5 ..\\gfx\\patset0.gl5 patset0.obj

leveldef.dat : leveldef.asm level.inc palete.asm font.asm fontspr.asm
	as leveldef.asm
	ld /R8000 leveldef.dat=leveldef.rel

height0.dat : data\\height0.dat
	copy data\\height0.dat

height1.dat : data\\height1.dat
	copy data\\height1.dat

map0.dat : data\\map0.dat
	copy data\\map0.dat

map1.dat : data\\map1.dat
	copy data\\map1.dat

map2.dat : data\\map2.dat
	copy data\\map2.dat

map3.dat : data\\map3.dat
	copy data\\map3.dat

leveldef.inc : leveldef.rel
	export leveldef.sym > leveldef.inc

########################################################
#binary files


map0.bin : map0.dat loadpg2.obj bload.obj
	concat /B bload.obj + map0.dat + loadpg2.obj map0.bin

map1.bin : map1.dat loadpg3.obj bload.obj
	concat /B bload.obj + map1.dat + loadpg3.obj map1.bin

map2.bin : map2.dat loadpg4.obj bload.obj
	concat /B bload.obj + map2.dat + loadpg4.obj map2.bin

map3.bin : map3.dat loadpg5.obj bload.obj
	concat /B bload.obj + map3.dat + loadpg5.obj map3.bin

height0.bin : height0.dat loadpg6.obj bload.obj
	concat /B bload.obj + height0.dat + loadpg6.obj height0.bin

height1.bin : height1.dat loadpg7.obj bload.obj
	concat /B bload.obj + height1.dat + loadpg7.obj height1.bin

charset1.bin : charset1.obj loadpg11.obj bload.obj
	concat /B bload.obj + charset1.obj + loadpg11.obj charset1.bin

charset0.bin : charset0.obj loadpg10.obj bload.obj
	concat /B bload.obj + charset0.obj + loadpg10.obj charset0.bin

patset1.bin : patset1.obj loadpg9.obj bload.obj
	concat /B bload.obj + patset1.obj + loadpg9.obj patset1.bin

patset0.bin : patset0.obj loadpg8.obj bload.obj
	concat /B bload.obj + patset0.obj + loadpg8.obj patset0.bin

leveldef.bin : leveldef.dat loadpg1.obj bload.obj
	concat /B bload.obj + leveldef.dat + loadpg1.obj leveldef.bin


##########################################################
#sources

edpick.rel : edpick.asm shike2.inc level.inc bios.inc
	as $(ASFLAGS) edpick.asm

edobject.rel : edobject.asm shike2.inc level.inc data.inc event.inc bios.inc
	as $(ASFLAGS) edobject.asm

eddoor.rel : eddoor.asm data.inc shike2.inc level.inc event.inc
	as $(ASFLAGS) eddoor.asm

edchar.rel : edchar.asm shike2.inc bios.inc level.inc data.inc event.inc
	as $(ASFLAGS) edchar.asm

object.rel : object.asm data.inc level.inc
	as $(ASFLAGS) object.asm

door.rel : door.asm data.inc level.inc
	as $(ASFLAGS) door.asm

talk.rel : talk.asm sprite.inc data.inc shike2.inc
	as $(ASFLAGS) talk.asm

char.rel : char.asm bios.inc data.inc event.inc level.inc
	as $(ASFLAGS) char.asm

script.rel : script.asm data.inc shike2.inc
	as $(ASFLAGS) script.asm

movable.rel : movable.asm bios.inc shike2.inc data.inc level.inc
	as $(ASFLAGS) movable.asm

mob.rel : mob.asm bios.inc shike2.inc data.inc
	as $(ASFLAGS) mob.asm

game.rel : game.asm data.inc
	as $(ASFLAGS) game.asm

level.rel : level.asm shike2.inc bios.inc level.inc leveldef.inc data.inc
	as $(ASFLAGS) level.asm

edlevel.rel : edlevel.asm shike2.inc level.inc bios.inc event.inc
	as $(ASFLAGS) edlevel.asm

edneigh.rel : edneigh.asm shike2.inc level.inc bios.inc event.inc
	as $(ASFLAGS) edneigh.asm

map.rel : map.asm shike2.inc level.inc bios.inc
	as $(ASFLAGS) map.asm

edtsel.rel : edtsel.asm bios.inc shike2.inc event.inc level.inc
	as $(ASFLAGS) edtsel.asm

edfloor.rel : edfloor.asm bios.inc shike2.inc event.inc level.inc
	as $(ASFLAGS) edfloor.asm

edmap.rel : edmap.asm bios.inc shike2.inc level.inc event.inc sprite.inc
	as $(ASFLAGS) edmap.asm

edtile.rel : edtile.asm
	as $(ASFLAGS) edtile.asm

editor.rel : editor.asm shike2.inc bios.inc level.inc event.inc
	as $(ASFLAGS) editor.asm

mouse.rel : mouse.asm bios.inc sprite.inc shike2.inc
	as $(ASFLAGS) mouse.asm

zbuffer.rel : zbuffer.asm shike2.inc bios.inc
	as $(ASFLAGS) zbuffer.asm

stdlib.rel : stdlib.asm shike2.inc bios.inc
	as $(ASFLAGS) stdlib.asm

vdp.rel : vdp.asm shike2.inc bios.inc
	as $(ASFLAGS) vdp.asm

shike2.rel : shike2.asm shike2.inc bios.inc
	as $(ASFLAGS) shike2.asm

bios.rel : bios.asm bios.inc shike2.inc
	as $(ASFLAGS) bios.asm

kbd.rel : kbd.asm shike2.inc bios.inc event.inc
	as $(ASFLAGS) kbd.asm

shike2.com : $(REL)
	ld /R0100 /P0100 /D5000 /X /Gmain & < ld.cmd

clean :
	del *.rel > NUL
	del *.sym > NUL
	del *.com > NUL
	del *.bin > NUL
	del *.obj > NUL
	del shike2.lzh > NUL
	del palete.asm > NUL
	del font.asm > NUL
	del fontspr.asm > NUL
	del leveldef.inc > NUL
	del leveldef.dat > NUL
	del make$$$$.bat > NUL

