
	INCLUDE	BIOS.INC

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	PUBLIC	MOUSEHOOK,MOUSEX,MOUSEY
	EXTRN	SEXPAND

MOUSEHOOK:
	LD	A,(MPORT)
	OR	A
	RET	Z
	CALL	GTPAD			;CHECK MOUSE POSITION
	LD	HL,(MOUSEX)
	LD	H,0
	LD	DE,(SAVEX)
	CALL	SEXPAND			;CONVERT X INCREMENT TO 16 BITS
	ADD	HL,DE
	LD	DE,255
	CALL	ADJUST			;CHECK CORRECT POSITION
	LD	(MOUSEX),A

	LD	HL,(MOUSEY)
	LD	H,0
	LD	DE,(SAVEY)
	CALL	SEXPAND			;CONVERT Y INCREMENT TO 16 BITS
	ADD	HL,DE
	LD	DE,211
	CALL	ADJUST			;CHECK CORRECT POSITION
	LD	(MOUSEY),A
	RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;INPUT:	HL = COORDENATE
;	DE = LIMIT
;OUTPUT:A = ADJUSTED COORDENATED

	CSEG

ADJUST:	LD	A,H
	BIT	7,H
	JR	NZ,A.NEG

	CALL	DCOMPR
	JP	NC,A.BIG
	LD	A,L
	RET

A.NEG:	XOR	A
	RET

A.BIG:	LD	A,E
	RET


MPORT:	DB	16

	DSEG
MOUSEX:	DB	0
MOUSEY:	DB	0

