	INCLUDE	SHIKE2.INC
	INCLUDE	BIOS.INC

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	PUBLIC	MAIN
	EXTRN	BZERO,SETISR,CHKMSX,INITVDP,EDLEVEL,KBDCLR,GAME

MAIN:

	.PHASE	100H
.RELOC:
	LD	HL,.RELOC
        LD	DE,CODESEG
	LD	BC,CODESIZ
	LDIR
	JP	.CONT
	.DEPHASE

.CONT:	LD	HL,DATASEG
	LD	BC,DATASIZ
	CALL	BZERO		;CLEAR THE DATA SEGMENT

	LD	HL,0
	ADD	HL,SP
	LD	(E.RET),HL

	CALL	CHKMSX
	RET	Z		;THIS MSX HAS SOME PROBLEM FOR US

	CALL	INITVDP
	CALL	SETISR		;SET GAME ISR
	CALL	KBDCLR		;CLEAR KEYBOARD BUFFER
	CALL	EDLEVEL
	CALL	GAME

	;CONTINUE IN EXIT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

	CSEG
	PUBLIC	EXIT
	EXTRN	RESISR

EXIT:	CALL	RESISR		;RESTORE SYSTEM ISR
	EI
	XOR	A
	CALL	CHGMOD
	CALL	KILBUF
	LD	SP,(E.RET)
	RET

	DSEG
E.RET:	DW	0

